apiVersion: v1
kind: Pod
metadata:
  name: myenvpod
spec:
  containers:
  - name: shell
    image: alpine
    env:
      - name: MY_SECRET
        valueFrom:
            secretKeyRef:
                name: my-secret
                key: secret.txt
    command:
      - "bin/ash"
      - "-c"
      - "sleep 10000"
