apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: shell
    image: alpine
    command:
      - "bin/ash"
      - "-c"
      - "sleep 10000"
    volumeMounts:
      - name: secretvol
        mountPath: "/tmp/my-secret"
        readOnly: true
  volumes:
  - name: secretvol
    secret:
      secretName: my-secret
